version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service1
      - service2

  service1:
    build: ./services/service1
    container_name: service1
    ports:
      - "8081:8081"

  service2:
    build: ./services/service2
    container_name: service2
    ports:
      - "8082:8082"
